### PR TITLE
Add rule S6848 (`jsx-a11y/no-static-element-interactions`): Non-interactive DOM elements should not have an interactive handler

### LINKED ISSUE #4286: Create rule S6848 (`jsx-a11y/no-static-element-interactions`): Non-interactive DOM elements should not have an interactive handler
[plugin rule](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-static-element-interactions.md#jsx-a11yno-static-element-interactions)

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #4286

### CODE REVIEW

**Comment by ilia-kebets-sonarsource** [comment]
This looks quite noisy, WDYT?

**Comment by yassin-kammoun-sonarsource** [comment]
> This looks quite noisy, WDYT?

Do you really think that ~400 issues is noisy?

**Comment by yassin-kammoun-sonarsource** [comment]
Can we merge?

**Review by ilia-kebets-sonarsource — APPROVED** [review]
LGTM

**Pull request merged**
