### PR TITLE
Change log level of line `Failed to parse file ...` from `error` to `warn`

### LINKED ISSUE #4586: Change log level of line `Failed to parse file ...`
Currently, we log them at `ERROR` level, and it leads to many noise from users.

```
ERROR: Failed to parse file [legacy/grid-packages/ag-grid-docs/documentation/src/components/expandable-snippet/ExpandableSnippet.tsx] at line 423: Unexpected token. Did you mean `{'}'}` or `&rbrace;`?
```

### PR DESCRIPTION
**Pull request by ericmorand-sonarsource**
Fixes #4586

### CODE REVIEW

**Review by ilia-kebets-sonarsource — APPROVED** [review]
LGTM!

**Comment by ilia-kebets-sonarsource** [comment]
- cover the change for CSS as well
- unify log message: `Failed to parse file ...`

**Comment by ericmorand-sonarsource** [comment]
@ilia-kebets-sonarsource  checks are successful.

**Review by ilia-kebets-sonarsource — APPROVED** [review]
LGTM!

**Pull request merged**
