### PR TITLE
Release eslint-plugin-sonarjs version 2.0.0 with tag latest

### PR DESCRIPTION
**Pull request by vdiez**

### CODE REVIEW

**Review by ilia-kebets-sonarsource — APPROVED** [review]
LGTM

**Comment by karlhorky** [comment]
Is there a changelog for this anywhere?

I can't see any mention of this in:

1. [The GitHub Releases](https://github.com/SonarSource/SonarJS/releases) (which seem outdated)
2. [The repository search](https://github.com/search?q=repo%3ASonarSource%2FSonarJS+path%3A**%2Fchangelog&type=code)

The closest thing that I can find is a generated npm package diff like [this one from Renovate](https://app.renovatebot.com/package-diff?name=eslint-plugin-sonarjs&from=1.0.4&to=2.0.0), but since so many things moved, it seems unreadable

**Comment by karlhorky** [comment]
[Socket Security is reporting new capabilities in the v2.0.0 version](https://github.com/upleveled/eslint-config-upleveled/pull/416#issuecomment-2305162790), so a changelog would help build trust :)

Screenshot 2024-08-22 at 18 38 08

**Comment by vdiez** [comment]
Hi @karlhorky,

there are no specific release notes for the eslint plugin. This new 2.0.0 version was announced in the [previous repository](https://github.com/SonarSource/eslint-plugin-sonarjs), which will be archived in the coming weeks.

We'll think about a proper way to have release notes properly generated.

The main change is that it does now contain all rules from SonarJS instead of a subset. If you have questions about specific rules let us know. We are not accessing network in any of the rules, but we are using the `net` module from Node.js to parse IPs. As for filesystem, we search for parent `package.json` files to know if a project has certain dependencies.

Cheers

**Comment by karlhorky** [comment]
Nice, thanks for the first introduction to 2.0.0 and explanation of the permissions! Looking forward to the full release notes when they are available.

If you're looking for a solution, many in the Node.js ecosystem have adopted [Changesets](https://github.com/changesets/changesets) - maybe also a nice thing for `eslint-plugin-sonarjs`

> This new 2.0.0 version was announced in the [previous repository](https://github.com/SonarSource/eslint-plugin-sonarjs), which will be archived in the coming weeks.

Oh ok, I assume the announcement was the readme change here? Or was there something else too?

- https://github.com/SonarSource/eslint-plugin-sonarjs/pull/478

**Comment by vdiez** [comment]
Nothing else, some small announcement in the [Sonar Community Roundup](https://community.sonarsource.com/t/sonar-community-roundup-july-20-26/119770), but that's it.

Thanks for the hint on changesets, we'll have a look!

**Pull request merged**
