### PR TITLE
Use babel-eslint when parsing VueJS

### LINKED ISSUE #1978: Support 'import()' in VueJS files
`import()` syntax is a proposal at stage 4. It's supported by babel eslint parser, but not by eslint default parser. As for VueJS we use https://www.npmjs.com/package/vue-eslint-parser without specifying underlying parser, default eslint parser is used. We should specify `babel-eslint` in the parser options.
```
"parserOptions": {
    "parser": "babel-eslint",
    ...
}
```

https://github.com/tc39/proposal-dynamic-import

### PR DESCRIPTION
**Pull request by vilchik-elena**
Fixes #1978

### CODE REVIEW

**Comment by kakaru1331** [comment]
Hello! First I really appreciate your works. Thank you.
BTW can you tell me when will this be applied to sonar-scanner?

**Comment by IGx89** [comment]
Looks like this was released over a month ago in v6.3.0, but the Marketplace hasn't been updated with that version yet (latest there is still 6.2.1, while latest here is 6.4.1). You could manually install it -- I'm running into this same issue and will have to do that myself if the Marketplace isn't updated soon.

**Comment by kakaru1331** [comment]
@IGx89 Oh you saved my life. I'll try it!
thank you :D

**Comment by 0m4r** [comment]
> Looks like this was released over a month ago in v6.3.0, but the Marketplace hasn't been updated with that version yet (latest there is still 6.2.1, while latest here is 6.4.1). You could manually install it -- I'm running into this same issue and will have to do that myself if the Marketplace isn't updated soon.

how can I install manually the version that solves this issue?
I'd like to get this running with the sonarLint extention for VS Code

**Comment by IGx89** [comment]
Can't answer about SonarLint, don't use it myself. However, my guess is that for whatever reason they're holding all these new versions back for the next version of SonarQube, 8.5. Last I heard they were targeting to release that end of Sept. and the online docs already say 8.5, so it should be releasing shortly and then hopefully this whole confusing situation will be in the past...

**Comment by IGx89** [comment]
I can confirm SQ 8.5 contains the latest release of SonarJS (6.5)! Download links on sonarqube.org are still for 8.4, but I found a direct link elsewhere: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-8.5.0.37579.zip

**Pull request merged**
