### PR TITLE
Fixes #2658 - allow await on transient properties

### LINKED ISSUE #2658: FP S4123 (no-invalid-await): TypeScript `Pick` type
Creating new issue as requested by @vilchik-elena in #2636 

The following TypeScript code snippet creates a “Refactor this redundant ‘await’ on a non-promise.” warning, which is incorrect.

```typescript
interface MyQuery<T> extends Pick<Promise<T>, keyof Promise<T>> {
  toQuery(): string;
}

export async function demo(query: MyQuery<string>) {
  const result = await query;
  console.log(result);
}
```

image

I see the error both in the SonarLint VS Code plugin (v2.0.0) and the current version of SonarCloud.

The [`Pick`](https://www.typescriptlang.org/docs/handbook/utility-types.html#picktype-keys) type is a Typescript "utility" type.  It creates a dynamic interface.  For example `Pick<Todo, "title" | "completed">` would be an interface with only the "title" and "completed" fields in the "Todo" interface.

The [`keyof`](https://www.typescriptlang.org/docs/handbook/2/keyof-types.html) operator returns all of the keys/members of a type.

As far as I can tell, these should be equivalent:

```typescript
interface MyQuery<T> extends Pick<Promise<T>, keyof Promise<T>> {
  toQuery(): string;
}

interface MyQuery<T> extends Promise<T> {
  toQuery(): string;
}
```

To be candid, I don't use either of these features myself.  This is just my understanding.  

My project uses [Knex](https://github.com/knex/knex), which is a popular SQL builder.  Knex uses this pattern extensively, and then creates many false positives. 

Here is the root declaration in Knex:

https://github.com/knex/knex/blob/dfbc76b915fff9f40e806ac2e0aafe8e4e5b6965/types/index.d.ts#L1742

```typescript
interface ChainableInterface<T = any> extends Pick<Promise<T>, keyof Promise<T> & ExposedPromiseKeys>, StringTagSupport {
  generateDdlCommands(): Promise<{ pre: string[], sql: string[], post: string[] }>;
  toQuery(): string;
```

_Originally posted by @codyebberson in https://github.com/SonarSource/SonarJS/issues/2636#issuecomment-854097749_

### PR DESCRIPTION
**Pull request by codyebberson**
Fixes #2658 - see issue for more details

### CODE REVIEW

**Comment by codyebberson** [comment]
From the build failure:

```
yarn config set registry "${ARTIFACTORY_URL}/api/npm/npm"
/tmp/scripts52fdfc072182654f163f5f0f9a621d72.sh: line 6: ARTIFACTORY_URL: unbound variable
```

This seems unrelated to the files changed.

**Comment by spartanatreyu** [comment]
Is there something holding this back?

Not being able to use promises/async/await in JS/TS files is a big deal when all modern libraries are built upon them.

I can't trust the linter until this is fixed.

**Comment by codyebberson** [comment]
@spartanatreyu - see https://github.com/SonarSource/SonarJS/issues/2636#issuecomment-878330083

My understanding is that they found some deeper issues with the tsconfig, so we're waiting for that.

**Comment by spartanatreyu** [comment]
Ah, I can see it on the [8.3 milestone](https://github.com/SonarSource/SonarJS/milestone/42) now, awesome.

**Comment by vilchik-elena** [comment]
Closing PR, it will be merged as part of https://github.com/SonarSource/SonarJS/pull/2755 (with a different approach applied)

**Pull request closed without merging**
