### PR TITLE
Migrate S1534 to eslint implementation (no-dupe-keys)

### LINKED ISSUE #2091: Migrate S1534 to eslint implementation (no-dupe-keys) for JS

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #2091 

--
The issues for the jshint project are no longer raised because the involved Javascript file includes non-parsable code in strict mode, e.g. getters with parameters generate a parsing error.

### CODE REVIEW

**Review by guillaume-dequenne-sonarsource — CHANGES_REQUESTED** [review]
With now only 1 case reported on the ruling, I'm afraid our testing is a bit light. Also, the behaviour of the rule is not tested for TS code.
Could you please add a `file-for-rules` folder in `typescript-test-sources` and maybe add some code that would raise an issue (maybe inspired from our previous test cases) ?

**Comment by yassin-kammoun-sonarsource** [comment]
Actually, the rule does not apply to TypeScript as the compiler would detect duplicate properties and raise a compilation error.

**Comment by guillaume-dequenne-sonarsource** [comment]
Fair enough! Could you still please add some of our test cases to the ruling sources for JavaScript so that we can keep some tests for the behaviour of this rule?

**Review by guillaume-dequenne-sonarsource — APPROVED** [review]

**Review by guillaume-dequenne-sonarsource — APPROVED** [review]
lgtm

**Pull request merged**
