### PR TITLE
Upgrade embedded Node.js

### PR DESCRIPTION
**Pull request by ericmorand-sonarsource**

### CODE REVIEW

**Review by yassin-kammoun-sonarsource — COMMENTED** [review]
@ericmorand-sonarsource There is this [ticket](https://sonarsource.atlassian.net/browse/JS-275) part of the hardening.
Let's update the PR title to include the Jira ticket number.
Also, could you try to upgrade to Node.js 22?

**Comment by ericmorand-sonarsource** [comment]
> @ericmorand-sonarsource There is this [ticket](https://sonarsource.atlassian.net/browse/JS-275) part of the hardening. Let's update the PR title to include the Jira ticket number. Also, could you try to upgrade to Node.js 22?

The release documentation says that we should upgrade to the most recent Node.JS LTS:

> Before each release, this runtime should be updated to the latest LTS available

https://xtranet-sonarsource.atlassian.net/wiki/spaces/LANG/pages/2949283923/How+to+upgrade+the+SonarJS+Node.js+embedded+runtime

This PR is only taking care of that.

**Comment by saberduck** [comment]
I suggest we wait until Node.js 22 is official LTS (mid October) and do this change with JS-275

**Comment by ericmorand-sonarsource** [comment]
After agreement with the team on @saberduck proposal to wait for Node.JS 22 LTS, I close this PR.

**Pull request closed without merging**
