### PR TITLE
Ignore promises in S3735 void-use

### LINKED ISSUE #2629: Ignore promises in S3735 `void-use`
eslint@typescript-eslint/no-floating-promises is reporting when promise is used not being used and suggests to add `void` to be explicit that value is ignore.
```
  const exampleFunction = () => { return new Promise(() => {});};
  void exampleFunction();
```

For such code rule S3735 will report that `void` should not be used. We should improve S3735 to not report when void argument has promise type.
 
Reported in https://community.sonarsource.com/t/typescript-void-should-not-be-used-triggers-wrongly/41893

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #2629

### CODE REVIEW

**Review by vilchik-elena — APPROVED** [review]
LGTM. 

There are plenty issues like this on Peach, could you verify tomorrow that they are gone?

**Comment by yassin-kammoun-sonarsource** [comment]
Sure thing.

**Comment by navtejsohal7** [comment]
Hey Yassin, I am wondering, do we need to add anything into our code or sonarQube to make it work? OR is that something already implemented in sonarQube because I am still seeing this error a lot in my project

**Comment by yassin-kammoun-sonarsource** [comment]
Hello @navtejsohal7,

This change was introduced in SonarQube 8.8. Maybe you are using an older version. If this is not the case, I suggest you report the false positive you are encountering in https://community.sonarsource.com.

**Comment by mmospanenko** [comment]
Add void - sonarlint(typescript:S3735)
Remove void - @typescript-eslint/no-floating-promises

how to be?

**Pull request merged**
