### PR TITLE
Add rule S6353: Regular expression quantifiers and character classes should be used concisely

### LINKED ISSUE #2778: Add rule S6353: Regular expression quantifiers and character classes should be used concisely
https://sonarsource.github.io/rspec/#/rspec/S6353/javascript

### PR DESCRIPTION
**Pull request by yassin-kammoun-sonarsource**
Fixes #2778

### CODE REVIEW

**Review by saberduck — CHANGES_REQUESTED** [review]
it seems that `[\s\S]` is an idiom used to match also newline character, which is by default not matched by `.`  I think we can still keep the rule, but I would detail this in the rule description and also adjust the message that if newline should be matched, this should be set by using `s` flag

**Comment by yassin-kammoun-sonarsource** [comment]
> it seems that `[\s\S]` is an idiom used to match also newline character, which is by default not matched by `.` I think we can still keep the rule, but I would detail this in the rule description and also adjust the message that if newline should be matched, this should be set by using `s` flag

I was not aware of that, and I think it's better to update the rule implementation so that `[\s\S]` is only considered when the `s` flag is enabled.

**Review by saberduck — APPROVED** [review]

**Comment by saberduck** [comment]
@yassin-kammoun-sonarsource can you also update description of the rule about `\s\S` and `s` flag?

**Comment by yassin-kammoun-sonarsource** [comment]
> @yassin-kammoun-sonarsource can you also update description of the rule about `\s\S` and `s` flag?

@saberduck Sure thing. Could you review first [this change](https://github.com/SonarSource/rspec/pull/297) ?

**Pull request merged**
